name: Code quality
on:
  push:
env:
  UV_SYSTEM_PYTHON: 1

jobs:

  run:
    runs-on: ubuntu-latest

    steps:

      - name: Acquire sources
        uses: actions/checkout@v4.1.1

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12"
          architecture: x64

      - name: Apply caching of dependencies
        uses: actions/cache@v4.0.0
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('**/requirements-*.txt') }}

      - name: Install dev dependencies
        run: uv pip install -r dev-requirements.txt

      - name: Run ruff
        run: |
          ruff format --diff .
          ruff check --diff .